all: linux32-dbg linux32 linux64-dbg linux64 win32-dbg win32 win64-dbg win64

## Linux32 Debug
linux32-dbg: FileAESCrypt.cpp
	g++ -m32 -DNDEBUG -g2 -O2 -I . FileAESCrypt.cpp ./lib/debug/libcryptopp.a -o bin/debug/FileAESCrypt-dbg.bin
## Linux32 Release
linux32: FileAESCrypt.cpp
	g++ -m32 -march=native -O3 -I . FileAESCrypt.cpp ./lib/libcryptopp.a -o bin/FileAESCrypt.bin

## Linux64 Debug
linux64-dbg: FileAESCrypt.cpp
	g++ -m64 -DNDEBUG -g2 -O2 -I . FileAESCrypt.cpp ./lib64/debug/libcryptopp.a -o bin64/debug/FileAESCrypt64-dbg.bin
## Linux64 Release
linux64: FileAESCrypt.cpp
	g++ -m64 -march=native -O3 -I . FileAESCrypt.cpp ./lib64/libcryptopp.a -o bin64/FileAESCrypt64.bin
		
## Windows 32-bit Debug
win32-dbg: FileAESCrypt.cpp
	i686-w64-mingw32-g++ -m32 -DNDEBUG -g2 -O2 -static -I . FileAESCrypt.cpp ./lib/win32debug/libcryptopp.a -o bin/win32debug/FileAESCrypt-dbg.exe
## Windows 32-bit Release
win32: FileAESCrypt.cpp
	i686-w64-mingw32-g++ -m32 -march=native -O3 -static -I . FileAESCrypt.cpp ./lib/win32release/libcryptopp.a -o bin/win32release/FileAESCrypt.exe

## Windows 64-bit Debug
win64-dbg: FileAESCrypt.cpp
	x86_64-w64-mingw32-g++ -m64 -DNDEBUG -g2 -O2 -static -I . FileAESCrypt.cpp ./lib64/win64debug/libcryptopp.a -o bin64/win64debug/FileAESCrypt64-dbg.exe
## Windows 64-bit Release
win64: FileAESCrypt.cpp
	x86_64-w64-mingw32-g++ -m64 -march=native -O3 -static -I . FileAESCrypt.cpp ./lib64/win64release/libcryptopp.a -o bin64/win64release/FileAESCrypt64.exe
